#'Use the model generated by "LogReg" to predict new test data
#'
#' @param newx input matrix, of dimension n (sample number) by p (variable number);
#' each row is an observation vector.
#' @param fit the model generated by "LogReg".
#' Since we aim at binomial distribution, it should be either a factor with two levels,
#'  or a two-column matrix (every row is the probability of two class.)
#'  @return the prediction for every row of test data newx. And the label will be the same as that of training data.
#'
#'  @export
#'

My_predict<-function(fit,newx){
  n<-dim(newx)[1]
  X<-cbind(rep(1,n),newx)
  p<-dim(X)[2]
  result <- X%*%fit$x
  tmp <-rep(fit$label[2],n)
  tmp[which(result>0)]<-fit$label[1]
  return( tmp)
}
